backend:
  name: git-gateway
  repo: GeoSauer/next-decapcms-template #TODO edit this to your own github_username/repo or store it in a secret if you're using a private repo
  branch: main
media_folder: "public/images" # Location where files will be stored in the repo
public_folder: "/images" # Public path for uploaded media
# Here we define content structure
collections:
  - label: "Home page" # Used in UI
    name: "homepage" # Used in routes
    files:
      - label: "Hero"
        name: "hero"
        file: "src/content/homepage/hero.md" # Path to the markdown file
        create: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Background Image", name: "backgroundImage", widget: "image", required: false }
          - {
              label: "Background Image Alt Text",
              name: "backgroundImageAltText",
              widget: "string",
              required: false,
            }
          - { label: "Button Text", name: "buttonText", widget: "string" }
      - label: "Content Blocks"
        name: "content_blocks"
        file: "src/content/homepage/content_blocks.md"
        fields:
          - { label: "Section Title", name: "sectionTitle", widget: "string" }
          - label: "Contents"
            name: "contents"
            widget: "list" # A list of content objects
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Section Content", name: "sectionContent", widget: "markdown" }
