backend:
  name: git-gateway
  repo: GeoSauer/nextjs-decapcms-template #TODO change to your GitHub/repo
  branch: main
  identity_url: "https://nextjs-decapcms-template.netlify.app/.netlify/identity" #TODO change to your Netlify site URL
media_folder: "public/images" # Location where files will be stored in the repo
public_folder: "/images" # Public path for uploaded media

# Here we define content structure
collections:
  - label: "Home page" # Used in UI
    name: "home_page" # Used in routes
    files:
      - label: "Hero"
        name: "hero"
        file: "src/content/home-page/hero.md" # Path to the markdown file
        create: false
        delete: false
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "Description", widget: "text" }
          - name: "details"
            label: "Details"
            widget: "object"
            fields:
              - { name: "text", label: "Details Text", widget: "string" }
              - { name: "link", label: "Details Link", widget: "string" }
              - { name: "url", label: "Details URL", widget: "string" }
          - name: "cta"
            label: "CTA Button"
            widget: "object"
            fields:
              - { name: "text", label: "Button Text", widget: "string" }
              - { name: "url", label: "Button URL", widget: "string" }
      - label: "Info Blocks"
        name: "info_blocks"
        file: "src/content/home-page/info_blocks.md"
        create: true
        fields:
          - { label: "Section Title", name: "sectionTitle", widget: "string" }
          - label: "Blocks"
            label_singular: "Info Block"
            name: "blocks"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown", required: false }
