backend:
  name: git-gateway
  repo: GeoSauer/nextjs-decapcms-template #TODO change to your GitHub/repo
  branch: main
  identity_url: "https://nextjs-decapcms-template.netlify.app/.netlify/identity" #TODO change to your Netlify site URL
media_folder: "public/images" # Location where files will be stored in the repo
public_folder: "/images" # Public path for uploaded media
# Here we define content structure
collections:
  - label: "Home page" # Used in UI
    name: "homepage" # Used in routes
    files:
      - label: "Hero"
        name: "hero"
        file: "src/content/homepage/hero.md" # Path to the markdown file
        create: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Background Image", name: "backgroundImage", widget: "image", required: false }
          - {
              label: "Background Image Alt Text",
              name: "backgroundImageAltText",
              widget: "string",
              required: false,
            }
          - { label: "Button Text", name: "buttonText", widget: "string" }
      - label: "Info Blocks"
        name: "info_blocks"
        file: "src/content/home-page/info_blocks.md"
        create: true
        fields:
          - { label: "Section Title", name: "sectionTitle", widget: "string" }
          - label: "Blocks"
            label_singular: "Info Block"
            name: "blocks"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown", required: false }
