backend:
  name: git-gateway
  repo: GeoSauer/nextjs-decapcms-template #TODO change to your GitHub/repo
  branch: main
  identity_url: "https://nextjs-decapcms-template.netlify.app/.netlify/identity" #TODO change to your Netlify site URL
media_folder: "public/images" # Location where files will be stored in the repo
public_folder: "/images" # Public path for uploaded media

# Here we define content structure
collections:
  - label: "Home page" # Used in UI
    name: "home_page" # Used in routes
    files:
      - label: "Hero"
        name: "hero"
        file: "src/content/home-page/hero.md" # Path to the markdown file
        create: false
        delete: false
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "Description", widget: "text" }
          - name: "details"
            label: "Details"
            widget: "object"
            fields:
              - { name: "text", label: "Text", widget: "string" }
              - { name: "link", label: "Link", widget: "string" }
              - { name: "url", label: "URL", widget: "string" }
          - name: "cta"
            label: "CTA Button"
            widget: "object"
            fields:
              - { name: "text", label: "Button Text", widget: "string" }
              - { name: "url", label: "Button URL", widget: "string" }
      - label: "Features"
        name: "features"
        file: "src/content/home-page/features.md"
        widget: "object"
        create: true
        fields:
          - name: "developers"
            label: "Developer Features"
            label_singular: "Dev Feature"
            widget: "list"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "description", label: "Description", widget: "text" }
          - name: "clients"
            label: "Client Features"
            label_singular: "Client Feature"
            widget: "list"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "description", label: "Description", widget: "text" }
      - label: "Examples"
        name: "examples"
        file: "src/content/home-page/examples.md"
        fields:
          - name: "title"
            label: "Section Title"
            widget: "string"
          - name: "pages"
            label: "Pages"
            label_singular: "Page"
            widget: "list"
            create: true
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "url", label: "URL", widget: "string" }
              - { name: "image", label: "Image", widget: "image" }
              - { name: "alt", label: "Alt Text", widget: "string", required: false }
      - label: "Contact Form"
        name: "contact"
        file: "src/content/home-page/contact.md"
        fields:
          - { name: "show", label: "Show Form", widget: "boolean" }
          - { name: "title", label: "Title", widget: "string" }
          - { name: "subtitle", label: "Subtitle", widget: "string" }
